In [8]:
import numpy as np

c = np.array([[1,2,3],
             [4,5,6]])
print(c.dtype)
print(c.itemsize)
print(c.data)

int32
4


In [35]:
u = np.arange(6).reshape(2,3)
v = np.arange(6,12).reshape(2,3)

# print(u)
print(v)

# print(u @ u.T)

print(v.argmax(axis=0))

[[ 6  7  8]
 [ 9 10 11]]
[1 1 1]


In [45]:
import pandas as pd
from collections import Counter

df = pd.read_json('spider_items.jl', lines=True)

stocked_in = df[:80]
new_arrival = df[80:].reindex()
del new_arrival['tags']

In [58]:
from collections import Counter

# print(stocked_in['text'])
counter = Counter()
for item in stocked_in['author']:
    print(item)

top_words = None

Albert Einstein
J.K. Rowling
Albert Einstein
Jane Austen
Marilyn Monroe
Albert Einstein
André Gide
Thomas A. Edison
Eleanor Roosevelt
Steve Martin
Marilyn Monroe
J.K. Rowling
Albert Einstein
Bob Marley
Dr. Seuss
Douglas Adams
Elie Wiesel
Friedrich Nietzsche
Mark Twain
Allen Saunders
Pablo Neruda
Ralph Waldo Emerson
Mother Teresa
Garrison Keillor
Jim Henson
Dr. Seuss
Albert Einstein
J.K. Rowling
Albert Einstein
Bob Marley
Dr. Seuss
J.K. Rowling
Bob Marley
Mother Teresa
J.K. Rowling
Charles M. Schulz
William Nicholson
Albert Einstein
Jorge Luis Borges
George Eliot
George R.R. Martin
C.S. Lewis
Marilyn Monroe
Marilyn Monroe
Albert Einstein
Marilyn Monroe
Marilyn Monroe
Martin Luther King Jr.
J.K. Rowling
James Baldwin
Jane Austen
Eleanor Roosevelt
Marilyn Monroe
Albert Einstein
Haruki Murakami
Alexandre Dumas fils
Stephenie Meyer
Ernest Hemingway
Helen Keller
George Bernard Shaw
Charles Bukowski
Suzanne Collins
Suzanne Collins
C.S. Lewis
J.R.R. Tolkien
J.K. Rowling
Ernest Hemingway
Ralph 